### ISSUE TITLE
deployment error - webpack

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/CAFECA-v2#30]
處理 #29 後, vercel 部署出現錯誤

```
**Failed to compile.

HookWebpackError: Unexpected '/'. Escaping special characters with \ may help.
    at makeWebpackError (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
    at /Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
    at eval (eval at create (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:34:1)
-- inner error --
Error: Unexpected '/'. Escaping special characters with \ may help.
    at /Users/shirley/programming/cafeca/CAFECA-v2/static/css/4a7011742b6e011a.css:1499:1
    at Root._error (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:78465)
    at Root.error (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:124360)
    at Parser.error (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:86811)
    at Parser.unexpected (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:87297)
    at Parser.combinator (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:85544)
    at Parser.parse (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:92828)
    at Parser.loop (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:92233)
    at new Parser (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:78322)
    at Processor._root (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:95242)
    at Processor._runSync (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:95749)
caused by plugins in Compilation.hooks.processAssets
Error: Unexpected '/'. Escaping special characters with \ may help.
    at /Users/shirley/programming/cafeca/CAFECA-v2/static/css/4a7011742b6e011a.css:1499:1
    at Root._error (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:78465)
    at Root.error (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:124360)
    at Parser.error (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:86811)
    at Parser.unexpected (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:87297)
    at Parser.combinator (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:85544)
    at Parser.parse (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:92828)
    at Parser.loop (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:92233)
    at new Parser (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:78322)
    at Processor._root (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:95242)
    at Processor._runSync (/Users/shirley/programming/cafeca/CAFECA-v2/node_modules/next/dist/compiled/cssnano-simple/index.js:190:95749)


> Build failed because of webpack errors**
```

**Comment by arealclimber** [comment]
taking 0.5 hrs
